name: dart_serialport
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  glob: ^2.1.2
  linux_serial: ^0.2.3+6
  meta: ^1.9.1
  path: ^1.8.3
  stdlibc: ^0.1.4

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
